baseurl: "https://blog.lightsinger.top/"
languageCode: "en-us"
title: "令不言"
theme: "hugo-ivy"
disqusShortname: "lightsinger"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  # cn: "/:sections/:year/:month/:slug/"
  "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "首页/Home"
      url: "/"
      weight: 1
    - name: "标签/Tags"
      url: "/tags/"
      weight: 2
    - name: "阅读/Reading"
      url: "/cn/reading"
      weight: 3
    - name: "关于/About"
      url: "/cn/about/"
      weight: 4
    - name: "订阅/Rss"
      url: "/index.xml"

  # en:
  # - name: "Home"
  #   url: "/"
  #   weight: 1
  # - name: "About"
  #   url: "/about/"
  #   weight: 2
  # - name: ""
  #   url: "/en/"
  #   weight: 3
  # - name: "Vitae"
  #   url: "/vitae/"
  #   weight: 4
  # - name: "Todo"
  #   url: "/todo/"
  #   weight: 5
  # - name: "中文"
  #   url: "/cn/"
  #   weight: 6
  # cn:
  #   - name: "首页"
  #     url: "/"
  #     weight: 1
  #   - name: "关于"
  #     url: "/cn/about/"
  #     weight: 2
  #   - name: "日志"
  #     url: "/cn/"
  #     weight: 3
  #   - name: "书籍"
  #     url: "/cn/books"
  #     weight: 4
  #   - name: "English"
  #     url: "/en/"
  #     weight: 5

params:
  description: "为所爱奋不顾身"
  footer: "&copy; [令不言](https://blog.lightsinger.top)  | [twitter](https://twitter.com/zlc_milano)"
  disqusURL: "https://blog.lightsinger.top"
  utterancRepo: "imilano/imilano.github.io"
  utterancTheme: "github-light"
  utterancIssueTerm: "title"
  startYear: "2021"
  custom_css:
    - "css/custom.css"
    - "css/fonts.css"
  customJS:
    - "fix-toc.js"
    - "center-img.js"
    - "right-quote.js"
    - "no-highlight.js"
    - "fix-footnote.js"
    - "math-code.js"
    - "external-link.js"
    - "alt-title.js"
    - "header-link.js"
  githubContentURL: "https://github.com/imilano/imilano.github.io/edit/master/content/"
  twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "11.7.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  # highlightjsLang: ["r", "yaml", "tex", "go"]
  highlightjsTheme: "xcode"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Philos"
      tag: ""

  author:
    en: "Philos"
    cn: "令不言"
    # animation: "Yihui Xie & Lijia Yu"

  # lang:
  #   edit:
  #     cn: "编辑"
  #   license:
  #     cn: "版权"
  #   subscribe:
  #     cn: "订阅"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
